config/routes.rb
Rails.application.routes.draw do


	root to: 'top#home'

	devise_for :users

	resources :users, only: [:show, :index, :edit, :update] do
		resource :relationships, only: [:create, :destroy]
		get :follows, on: :member
		get :followers, on: :member
	end

	resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
		resource :favorites, only: [:create, :destroy]
		resources :book_comments, only: [:create, :destroy]
    end

	get '/home/about' => 'top#about', as: 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  attachment :profile_image

  validates :name, presence: true, length: {in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end


  def after_sign_in_path_for(resource)
  	flash[:notice] = "successfully Login"
  	user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
  	flash[:alert] = "successfully Logout"
  	root_path
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_to book_path(params[:book_id])
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
		
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def index
		@books = Book.all
		@user = current_user
		@book = Book.new
	end


	def create
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book), notice: 'post successfully'
	    else
	    	@user = User.find(current_user.id)
	    	@books = Book.all
	    	render :index
		end

	end



	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book.id), notice: 'update successfully'
		else
			render :edit
		end

	end

	def show
		@books = Book.find(params[:id])
		@user = @books.user
		@book = Book.new
		@book_comment = BookComment.new
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to user_path(current_user.id)
	end

	private
	def book_params
		params.require(:book).permit(:title, :body, :user_id)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.build(book_id: params[:book_id])
  	favorite.save
 
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
  	favorite.destroy

  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	follow = current_user.active_relationships.build(follower_id: params[:user_id])
  	follow.save
  	redirect_back(fallback_location: root_url)
  end

  def destroy
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
  	follow.destroy
  	redirect_back(fallback_location: root_url)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

def home
end


def about
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

 
  def index
  	@users = User.all
    @user = current_user
    @books = @user.books
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: 'update successfully'
    else
      render :edit
    end
  end

  private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image, :user_id)
	end

  def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>

  <body>
  	<div class="container">
      	<div class="row">
      		<div class="col-md-6 col-md-offset-3">
      			<h1>Editing Book</h1>
      			<%=form_for(@book) do |f| %>

               <% if @book.errors.any? %>
                  <%= @book.errors.count %>件のerrorが発生しました
                  <% @book.errors.full_messages.each do |message| %>
                    <%= message %>
                  <% end %>
               <% end %>

      			   <h2>Title</h2>
      			   <%= f.text_field :title %>

      			   <h2>Opinion</h2>
      			   <%= f.text_area :body %>

      			   <%= f.submit  'Update Book', class:"btn btn-primary btn-block" %>

      			<% end %>
      			<%= link_to "Show", book_path %> |
      			<%= link_to "Back", books_path %>
      		</div>
      		<div class="col-md-3">
      			
      		</div>
      	</div>
    </div>
  </body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          <table class="table">
            <tbody>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
              <tr>
                <th>フォロー数: </th>
                <th>
                  <%= link_to follows_user_path(@user.id) do %> 
                    <%= @user.followings.count %>
                  <% end %> 
                </th>
              </tr>
              <tr>
                <th>フォロワー数: </th>
                <th>
                  <%= link_to followers_user_path(@user.id) do %>
                    <%= @user.followers.count %>
                  <% end %>
                </th>
              </tr>
            </tbody>
          </table>

          <%= link_to edit_user_path(@user) do %>
            <button type="button" class="btn btn-default btn-block"> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
          <% end %>


          <h2>New book</h2>
          <%= form_for(@book) do |f| %>

            <% if @book.errors.any? %>
               <%= @book.errors.count %>件のerrorが発生しました
               <% @book.errors.full_messages.each do |message| %>
                   <%= message %>
               <% end %>
            <% end %>

            <h4>Title</h4>
            <%= f.text_field :title %>

            <h4>Opinion</h4>
            <%= f.text_area :body %>

            <%= f.submit  'Create Book', class:"btn btn-primary btn-block" %>
          <% end %>
        </div>

        <div class="col-xs-9">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
      			  	<th>Title</th>
      				  <th>Opinion</th>
      				  <th colspan="3"></th>
   				    </tr>
 		        </thead>
            <% @books.each do |book| %>
 		         <tbody>
               <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
               </td>
               <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
               </td>
               <td><p class="book_body"><%= book.body %></p></td>
               <td>
                <div id="favorites_buttons_<%= book.id %>">
                  <%= render partial: 'favorites/favorite', locals: { book: book} %>
                </div>
               </td>
               <td>
                 コメント数: <%= book.book_comments.count %>
               </td>
 		         </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          <table class="table">
            <tbody> 
              <tr>
                <th>name</th>
               <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
              <tr>
                <th>フォロー数: </th>
                <th>
                  <%= link_to follows_user_path(@user.id) do %> 
                    <%= @user.followings.count %>
                  <% end %> 
                </th>
              </tr>
              <tr>
                <th>フォロワー数: </th>
                <th>
                  <%= link_to followers_user_path(@user.id) do %>
                    <%= @user.followers.count %>
                  <% end %>
                </th>
              </tr>
            </tbody>
          </table>

          <% if current_user == @user %>

            <%= link_to edit_user_path(@user) do %>
               <button type="button" class="btn btn-default btn-block"> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
            <% end %>

          <% else %>

            <% if current_user != @user %>
                <% if @user.followed_by?(current_user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class:"btn btn-primary btn-block" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-success btn-block" %>
                <% end %>
            <% end %>

          <% end %>

          <h2>New book</h2>
          <%= form_for(@book) do |f| %>

            <% if @book.errors.any? %>
               <%= @book.errors.count %>件のerrorが発生しました
               <% @book.errors.full_messages.each do |message| %>
                   <%= message %>
               <% end %>
            <% end %>

            <h4>Title</h4>
            <%= f.text_field :title %>

            <h4>Opinion</h4>
            <%= f.text_area :body %>

            <%= f.submit  'Create Book', class:"btn btn-primary btn-block" %>
          <% end %>
        </div>

  	    <div class="col-xs-9">
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><%= @user.name %>
                  <% end %>
                </td>
                <td><p class="book_title"><%= @books.title %></p></td>
                <td><p class="book_body"><%= @books.body %></p></td>

                <td>
                  <div id="favorites_buttons_<%= @books.id %>">
                    <%= render partial: 'favorites/favorite', locals: { book: @books} %>
                  </div>
                </td>

                <td>
                  コメント数: <%= @books.book_comments.count %>
                </td>

                <% if @books.user == current_user %>
                  <td><%= link_to "Edit", edit_book_path(@books), class: "btn btn-success pull-right" %></td>
                  <td><%= link_to "Destroy", book_path(@books), method: :delete, class: "btn btn-danger pull-right" %></td>
                <% end %>

  				    </tr>
  			    </tbody>
  		    </table>

          <ol>
            <% @books.book_comments.each do |book_comment| %>

                <div class="comment-body bb">

                  <div class="comment-text">
                    <div class="comment-entry"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><%= book_comment.comment %></div>
                  </div>
                  <div class="comment-author clearfix">
                      <%= link_to user_path(book_comment.user) do %>
                        <%= book_comment.user.name %></a>
                      <% end %>
                  </div>
                  <% if book_comment.user == current_user%>
                    <div>
                      <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
                    </div>
                  <% end %>

                </div>

            <% end %>
          </ol>

          <%= form_for [@books, @book_comment] do |f| %>

                <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>

            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
          <% end %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/favorites/_favorite.html.erb
             
    <% if user_signed_in? %>
   
      <% if book.favorited_by?(current_user) %>
                  
        <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
            <%= book.favorites.count %> 
        <% end %>
                  
      <% else %>
                  
        <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            <%= book.favorites.count %> 
        <% end %>
                  
      <% end %>

    <% else %>

        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <%= book.favorites.count %>

    <% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row" style = "background-color:black;">
    <header>

        <nav>
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                <div class="list"><span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                <div class="list"><span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                <div class="list"><span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <div class="list"><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></div>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path do %>
                  <div class="list"><span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to about_path do %>
                  <div class="list"><span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                  <div class="list"><span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span></div>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <div class="list"><span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>

    </header>
  </div>
</div>

  <%= flash[:notice] %>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/top/about.html.erb
<!DOCTYPE html>
<html>
  <head>
	<style type="text/css">.turbolinks-progress-bar {
		position: fixed;
        display: block;
        top: 0;
        left: 0;
        height: 3px;
        background: #0076ff;
        z-index: 9999;
        transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
        transform: translate3d(0, 0, 0);
    }
    </style>
    <title>Bookers</title>
  </head>
  <body>
  	<div class="body">
      <div class="container">
      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>
    </div>
  </body>
</html>

app/views/top/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="csrf-param" content="authenticity_token">
  </head>

  <body>
    <header>
    </header>

    <div class="body">
      <div class="container">

        <div class="row">
          <div class="top-message col-md-offset-3 col-md-6">
            <h1>
              welcome to <span class="glyphicon glyphicon-book"></span> <strong>Bookers</strong>  !!
            </h1>
            <p>
              In <span class="glyphicon glyphicon-book"></span> <strong>Bookers</strong>, 
            </p>
            <p>
              you can share and exchange  your opinions , inpressions , and emotions
            </p>
            <p> about various books!</p>

            <div class="btn-wrapper">


              <%= link_to("Log in", new_user_session_path, {class: "btn btn-info btn-block"}) %>
              </div>

              <%= link_to("Sign up", new_user_registration_path, {class: "btn btn-success btn-block"}) %>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="container">
      <div class="row">
        <h2>User info</h2>
  	    <%= form_for(@user) do |f| %>

        <% if @user.errors.any? %>
            <%= @user.errors.count %>件のerrorが発生しました
            <% @user.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
        <% end %>

        <div>

  	      <h4>Name</h4>
  	      <%= f.text_field :name %>

  	      <h4>Introduction</h4>
  	      <%= f.text_area :introduction %>

        </div>
        <div>
          <div>
            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </div>
          <h4>Image</h4>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  	      <%= f.submit "Update User" %>
        </div>

  	    <% end %>
    </div>
   </div>
  </body>
</html>

app/views/users/followers.html.erb
<!DOCTYPE html>
<html>
	<body>
		<div class="container">
			<div class="row">
				<h2>Followers Users</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
                			<th>name</th>
                			<th colspan="3"></th>
              			</tr>
            		</thead>
            		<% @users.each do |user| %>
            			<tbody>
            				<tr>
            					<td>
            						<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                  				</td>
                  				<td>
                  					<%= user.name %>
                  				</td>
                  				<td>
                    				フォロー数: <%= user.followings.count %>
                  				</td>
                  				<td>
                    				フォロワー数: <%= user.followers.count %>
                  				<td>
                    				<%= link_to 'Show', user_path(user) %>
                  				</td>
                			</tr>
              	  		</tbody>
            		<% end %>
          		</table>
	  		</div>
	  	</div>
	</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          <table class="table">
            <tbody>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
              <tr>
                <th>フォロー数: </th>
                <th>
                  <%= link_to follows_user_path(@user.id) do %> 
                    <%= @user.followings.count %>
                  <% end %> 
                </th>
              </tr>
              <tr>
                <th>フォロワー数: </th>
                <th>
                  <%= link_to followers_user_path(@user.id) do %>
                    <%= @user.followers.count %>
                  <% end %>
                </th>
              </tr>
            </tbody>
          </table>

          <%= link_to edit_user_path(@user) do %>
            <button type="button" class="btn btn-default btn-block"> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
          <% end %>

          <h2>New book</h2>
          <%= form_for(@book) do |f| %>

            <% if @user.errors.any? %>
              <%= @user.errors.count %>件のerrorが発生しました
              <% @user.errors.full_messages.each do |message| %>
                <%= message %>
              <% end %>
            <% end %>

            <h4>Title</h4>
            <%= f.text_field :title %>

            <h4>Opinion</h4>
            <%= f.text_area :body %>
            <%= f.submit  'Create Book', class:"btn btn-primary btn-block" %>

          <% end %>
        </div>

        <div class="col-xs-9">
          <h2>Users</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @users.each do |user| %>
              <tbody>
                <tr>
                  <td>
                    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    フォロー数: <%= user.followings.count %>
                  </td>
                  <td>
                    フォロワー数: <%= user.followers.count %>
                  </td>
                  <td>
                    <% if current_user != user %>
                      <% if user.followed_by?(current_user) %>
                        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-primary btn-block" %>
                      <% else %>
                        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success btn-block" %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to 'Show', user_path(user) %>
                  </td>
                  <td>
                    コメント数: <%= user.book_comments.count %>
                  </td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          <table class="table">
            <tbody>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
              <tr>
                <th>フォロー数: </th>
                <th>
                  <%= link_to follows_user_path(@user.id) do %> 
                    <%= @user.followings.count %>
                  <% end %> 
                </th>
              </tr>
              <tr>
                <th>フォロワー数: </th>
                <th>
                  <%= link_to followers_user_path(@user.id) do %>
                    <%= @user.followers.count %>
                  <% end %>
                </th>
              </tr>
            </tbody>
          </table>

          <% if current_user == @user %>

            <%= link_to edit_user_path(@user) do %>
               <button type="button" class="btn btn-default btn-block"> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
            <% end %>

          <% else %>

            <% if current_user != @user %>
                <% if @user.followed_by?(current_user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class:"btn btn-primary btn-block" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-success btn-block" %>
                <% end %>
            <% end %>

          <% end %>

          <h2>New book</h2>
          <%= form_for(@book) do |f| %>

            <% if @user.errors.any? %>
                <%= @user.errors.count %>件のerrorが発生しました
                <% @user.errors.full_messages.each do |message| %>
                    <%= message %>
                <% end %>
            <% end %>

            <h4>Title</h4>
            <%= f.text_field :title %>

            <h4>Opinion</h4>
            <%= f.text_area :body %>

            <%= f.submit  'Create Book', class:"btn btn-primary btn-block" %>

          <% end %>
        </div>

        <div class="col-xs-9">
    	    <h2>Books</h2>
    	      <table class="table table-hover table-inverse">
    		      <thead>
    			      <tr>
    				      <th></th>
    				      <th>Title</th>
    				      <th>Opinion</th>
                  <th colspan="3"></th>
    			      </tr>
    		      </thead>
              <% @books.each do |book| %>
                <tbody>
                  <td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                  </td>
                  <td>
                    <%= link_to book_path(book) do %>
                      <%= book.title %>
                    <% end %>
                  </td>
                  <td><p class="book_body"><%= book.body %></p></td>
                </tbody>
              <% end %>
    	      </table>
        </div>
      </div>
    </div>
  </body>
</html>